# Generated by Django 3.1.12 on 2021-09-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('ReservaId', models.AutoField(primary_key=True, serialize=False)),
                ('Correo', models.EmailField(max_length=254)),
                ('Nombre', models.CharField(max_length=50)),
                ('Comuna', models.CharField(max_length=30)),
                ('Direccion', models.CharField(max_length=100)),
                ('Vehiculo', models.CharField(max_length=20)),
                ('Año', models.IntegerField()),
                ('Modelo', models.CharField(max_length=20)),
                ('Fecha', models.DateField()),
                ('Mensaje', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('TrabajadorId', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Correo', models.EmailField(max_length=254)),
                ('Telefono', models.IntegerField()),
                ('Direccion', models.CharField(max_length=100)),
                ('Contraseña', models.CharField(max_length=16)),
                ('Codigo', models.CharField(max_length=20)),
            ],
        ),
    ]
